### ISSUE TITLE
How do actions work?

### ISSUE THREAD

**Issue by matt-snider** [emersion/mako#125]
I've seen the following in the man pages and mentioned in other tickets but I don't see any examples or documentation of how it works:
* `--actions`
* `[actionable = ...]`
* `makoctl invoke [action]`

Would be great to see an example and documentation of this feature.

**Comment by vilhalmer** [comment]
Actions still haven't really been fleshed out: https://github.com/emersion/mako/issues/4.

The actionable criteria selects based on whether or not a notification has any attached to it, but this isn't super useful yet since there's no nice way to act on them. `makoctl invoke` likewise invokes the action by whatever name the notifying application gave it, but there's still no way to look them up (except peeking in on the bus when a notification is sent).

**Comment by matt-snider** [comment]
@vilhalmer Thanks for the info. 

It turns out I was just a bit confused. I use `notify-send` which doesn't allow actions AFAIK, so I didn't realize it was part of the standard (I guess [this](http://www.galago-project.org/specs/notification/0.9/x408.html) is a relevant resource).

I'll close this
