### ISSUE TITLE
Proposal: allow to change configuration via IPC

### ISSUE THREAD

**Issue by emersion** [emersion/mako#138]
We could add a makoctl command like this:

```
makoctl set [app-name="whatever"] border-color=red
```

These configuration options would be added to the current configuration. They would stay ephemeral, ie. `makoctl reload` would unset those.

The idea is to allow for things like:

- Temporarily hiding all notifications (ie. when doing a presentation or showing a screen to a third-party)
- Change the theme during the day
- Probably other things too

This would be similar to `swaymsg <command>`.

Thoughts?

**Comment by vilhalmer** [comment]
I like this idea, and it should be fairly easy to add since it would just involve inserting another criteria at the end of the list.

My main concern is that a long-running instance will start to collect a large number of criteria entries. This is especially true if something like this were used by scripting such for your time-of-day example. We haven't really explored the results of allowing them to build up.

A secondary concern is that some of the style options 'stack' in ways that can be somewhat non-intuitive, and would be difficult to cancel out without reloading the configuration and potentially losing other state that you would rather have kept.

I don't think either of these should block adding this though, as both can always be improved later on if they prove to be real problems. Something that could potentially fix/avoid both at the same time is adding some sort of user-defined name to criteria, which would then cause the style of that one to be changed when referenced rather than inserting a new one.

**Comment by CameronNemo** [comment]
Rather than going through dbus, it may be more natural to read any available configs in, for example `XDG_RUNTIME_DIR/mako/config.d`.

**Comment by emersion** [comment]
>My main concern is that a long-running instance will start to collect a large number of criteria entries. 

We can compare criteria, and merge the new one with an existing one if there is any.

>A secondary concern is that some of the style options 'stack' in ways that can be somewhat non-intuitive, and would be difficult to cancel out without reloading the configuration and potentially losing other state that you would rather have kept.

Hmm, do you have an example of this?

>Rather than going through dbus, it may be more natural to read any available configs in, for example $XDG_RUNTIME_DIR/mako/config.d.

Seems it would be more work for us and for the user.

**Comment by vilhalmer** [comment]
>Hmm, do you have an example of this?

Non-intuitive might be the wrong term. "Inconvenient" is probably more accurate. The order of the config file is important for things to behave the way you want, and adding new criteria at runtime may not interact with this very well.

Using the following hypothetical config file:
```
[app-name=Firefox]
background-color=#cccccc

[actionable]
background-color=#dd0000
```
The user expects the color of Firefox notifications to be overridden when they're actionable. If we create new criteria using IPC, attempting to change the color of normal Firefox notifications will break this behavior. (This is obviously contrived, but gets the point across.)

>We can compare criteria, and merge the new one with an existing one if there is any.

This would solve the above class of problem, but would introduce the reverse: it would be possible to make changes using IPC that have no apparent effect at all, because they're being overridden by something later in the config file. It could be fairly difficult to determine that this is the source of your problem.

I'm not sure which trade-off is better, though editing the existing criteria does at least fix the buildup problem.

**Comment by emersion** [comment]
Ah, I see. Indeed, this is an issue. Maybe we can forbid criteria as a first step, as it would still cover most of the use-cases.

I'd still prefer to change existing criteria blocks if they exist, since users can describe and order them in their config file. I wonder how Sway handles this.

**Comment by reversesh3ll** [comment]
This would be very useful when using a screen locker (swaylock etc). Ive been using dunst on i3 and sending "pkill -u "$USER" -USR1 dunst" to pause notifications received while the screen is locked. Then running "pkill -u "$USER" -USR2 dunst" to resume dunst, once screen locker quits (unlocked). This then allows all missed notifications to appear as usual. 

Is this currently possible with mako or would this issue need to be resolved first?

**Comment by emersion** [comment]
swaylock appears on top of mako, no need for this.

**Comment by vilhalmer** [comment]
It can appear above swaylock if configured to appear on the overlay layer. I use it this way so that it appears over fullscreen clients in sway, there's unfortunately no way to distinguish between secure and nonsecure clients here.

**Comment by emersion** [comment]
Oh, right. Yeah, and some people may prefer it one way or the other…

**Comment by reversesh3ll** [comment]
Its mainly for timed notifications that would otherwise be missed. Eg. Say a "download complete" notification that appears for 10 seconds, while the screen is locked. It will go unnoticed if it is under swaylock, or a breach of privacy if it is shown over the top of swaylock. Being able to pause all notifications, and not displaying them until after swaylock has been unlocked/killed, means you wont miss the notification but still retain your privacy. Hope my point makes sense.

**Comment by CameronNemo** [comment]
Would the issue not be present for any full screen top layer view? Can mako know when a notification has been seen, but not interacted with?

**Comment by vilhalmer** [comment]
Github, that was not a "closes" comment. -_-

**Comment by StephenBrown2** [comment]
But it was a "Closes" commit: https://github.com/emersion/mako/commit/79f9dd39cd0c5134f69f890911710ef883b912e1

**Comment by vilhalmer** [comment]
Yep, you're right. I pinged emersion to verify since I could go either way on closing this with just the global options in place, will re-close if appropriate shortly.

**Comment by emersion** [comment]
Referencing this important comment, food for thought: https://github.com/emersion/mako/pull/218#discussion_r365607600

**Comment by vilhalmer** [comment]
More thoughts:

It should be possible to fix many issues with positioning IPC configuration last in the list by having a mechanism for clearing options set over IPC rather than having the user explicitly set them to the opposite value. This prevents the IPC config, which is effectively a criteria which matches everything (`[]`), from continuing to override everything in the config file when the user instead expects to have undone their action.

This still only helps with critieria-less IPC config though. Need to think more on how to make it interact in an intuitive way.

I do have a new thought about how to merge IPC config with existing criteria, if we go that route. We could associate a second internal criteria with each one defined in the config file, like so (this is terrible ascii art, sorry):
```
[app-name=something]
|
 \ -- [(ipc) app-name=something]
|
[whatever]
|
 \ -- [(ipc) whatever]
```
The IPC criteria would always be applied after the original one. This allows you to change specific criteria while still retaining any overrides that would be applied later in the config file. It has the added benefit of allowing us to clear specific IPC changes instead of having to reload the entire config to get back the original values of options, which would be lost if we did a simple merge with the existing criteria.

This still doesn't help with the second issue described [above](https://github.com/emersion/mako/issues/138#issuecomment-483464991):
>it would be possible to make changes using IPC that have no apparent effect at all, because they're being overridden by something later in the config file. It could be fairly difficult to determine that this is the source of your problem.

I've still got nothing for that.

**Comment by xPMo** [comment]
Regarding overrides and config order:

*Would it be too late to define an order for criteria which supports most use cases, and ignore the order specified in the config file?*  For example, I would imagine most users would prefer config in `[urgency=high]` to override config in `[app-name=firefox]`.

In general, suppose `[a] < [b] < [c]` (`c` is highest priority, `a` is lowest.)
There are three ways I see to order:

- `[X a Y] < [X b Z]` for all (possibly empty, multi-critera) values of X, Y, Z. (e. g.: `[a c] < [b]`).
I believe this is tree sort/search.
- `[c] < [a b] == [b a]`, and `[a] == [a a] < [c]`, since `[a b]` is more specific than `[c]`.
- `[c] < [a b] == [b a]`, and `[a] < [c] < [a a]`.

I know the first option is well-ordered, but I haven't thought hard enough about the other two options.

ln either case, should a user desire to prefer an option to show up for firefox, even over the urgency hint styling, they can set the option in `[urgency=high app-name=firefox]` in addition to in the `[app-name=firefox]` section.

---

In any case, this completely outstrips the `wl_list` implementation currently used.

**Comment by emersion** [comment]
This has been superseded by https://github.com/emersion/mako/issues/335
