### ISSUE TITLE
Replace non-existent id

### ISSUE THREAD

**Issue by TheEdward162** [emersion/mako#167]
Hi,

recently I have started using `mako` instead of `dunst` and I noticed a difference in behaviour that I believe to be a bug.

If I call `notify-send.sh --print-id --replace 100 App Body`, the returned id is not 100 unless the notification with id 100 already exists. However, according to [the spec](http://www.galago-project.org/specs/notification/0.9/x408.html):

> If replaces_id is not 0, the returned value is the same value as replaces_id. 

the returned id should be the same as `--replace` id (no mention on whether or not the notification exists). Dunst does return the same id even for non-existent notifications.

I believe this was briefly touched on in #114 ([here exactly](https://github.com/emersion/mako/pull/114#discussion_r257463621)) but the current solution just creates a new notification with brand new id.

**Comment by vilhalmer** [comment]
Hmm. This really seems like the spec is contradicting itself. The description of the parameter earlier in the spec is:

>The optional notification ID that this notification replaces. The server must atomically (ie with no flicker or other visual cues) replace the given notification with this one. This allows clients to effectively modify the notification while it's active. A value of value of 0 means that this notification won't replace any existing notifications.

…which implies that it's only supposed to function if a notification with that id currently exists. This is also complicated by the fact that the spec explicitly endorses using incrementing integer ids, but allowing this can create a situation where the static id you've been using as `replaces_id` happens to be assigned to an unrelated notification.

That said, I'm not particularly opposed to changing this behavior since it makes it easier to interact with the notification, and the case where the ids collide is exactly one notification long.

**Comment by TheEdward162** [comment]
I don't think the spec is contradicting itself as much as just it doesn't really specify what to do in that case. It just all comes down to wording, really, as I would argue that you can "replace" a non-exitstent notification with an existing one.

As for the collision, it could either be ignored, or this case could be handled by keeping a separate HashSet or something similar with replaced ids and skipping those for new notifications. It might be worth looking at how dunst handles it as well.

Would you have time to implement this sometime soon™?

**Comment by emersion** [comment]
>Would you have time to implement this sometime soon™?

No. If you want something to happen, please send patches.
