### ISSUE TITLE
[Q] fullscreen notification

### ISSUE THREAD

**Issue by itapai** [emersion/mako#183]
I know I can set the layer option to overlay. This makes all the notifications show above fullscreen apps.

Is it possible to apply this behaviour to only some notifications, i.e. ones that have urgency critical? Or is there some other filter method?

Thanks

**Comment by emersion** [comment]
This is a feature request which is pretty similar to https://github.com/emersion/mako/issues/123

**Comment by vilhalmer** [comment]
This one is particularly tricky. While #123 could theoretically be implemented by making mako's drawing surface the size of the screen, having different notifications on different layers would require managing multiple layer shell surfaces.

Once we have ipc, it might be possible to rig something up so that when another window is in full screen, mako is instructed to ignore all but critical notifications. Then when you leave full screen, it would be told to start showing everything again. Then you just set it to always display on overlay. This is an annoying amount of state tracking, though.

**Comment by akvadrako** [comment]
Is it difficult to have multiple surfaces?

It seems like the most simple solution would be to just have multiple versions of mako running. I understand that’s a dbus limitation.

What if mako had an option to listen to a different dbus endpoint? Then a simple program could fan-out the notifications to both.

**Comment by vilhalmer** [comment]
I don't think we want to define a new defacto spec for multiple clients. Multiple surfaces would be the most reasonable way to do all of these things, but would create many complications with interactions between notifications.

For example, how should a notification that appears at a higher layer (and therefore a separate surface) be displayed if it sorts between two that appear at the default layer? We probably can't reasonably create one surface per notification without harming our ability to support high volumes of notifications and/or making the compositor unhappy. Even if we could, we don't have complete control over how the compositor may choose to lay out the surfaces.

**Comment by akvadrako** [comment]
Personally I would keep it simple. I don’t care about ordering between layers. I would put one on the left and one on the right - just two independent surfaces.

**Comment by vilhalmer** [comment]
This will be possible after #228.

**Comment by emersion** [comment]
Implemented in #228
