### ISSUE TITLE
FeatureRequest: first notification position offset

### ISSUE THREAD

**Issue by Stunkymonkey** [emersion/mako#236]
currently the notification is drawn over the pause-button, which makes it impossible to click while the notification is shown.
it would be better to first press pause and then the notification.
I would like to define an offset for the first notification.

temporary fix is: set it to a different anchor point.

**Comment by emersion** [comment]
Which pause button?

**Comment by Stunkymonkey** [comment]
in my case of a music-player
but this could happen in a video-player as well. e.g. vlc not in fullscreen with notifications in the bottom left

**Comment by emersion** [comment]
Ah, so it's a regular client. You can add an offset with `margin`.

**Comment by Stunkymonkey** [comment]
Yes this works, but it also changes the space between notifications. So it is not very pretty.
I would like to have an offset for the "first" notification, and all the rest stays the same

**Comment by emersion** [comment]
Ah, indeed. Maybe we'll want to add a style option for the first and last notifications? Maybe that could fix https://github.com/emersion/mako/pull/227 too?

**Comment by vilhalmer** [comment]
An alternative would be adding back support for layer-shell margins with a different option like `outer-margin` or similar. I kind of prefer a `first` critieria though.

**Comment by Ongy** [comment]
I think the first and last style options might have weird interactions iwth groups (would the entire group be first/last?)

Also requries recomputing styles every time any ntofication is added or removed (though I'm unsure if that happens for grouping already?)
And would have some rather weird interaction with the multi-surface work I'm doing^^

Maybe have a 4tuple (like margins) that decides whether to apply the margin to the outer-most notification in that direction? Currently only makes sense for top and bottom, since there's no horizontal notification layouting.

**Comment by Stunkymonkey** [comment]
is a new release planned? The last one is about a 3/4 year ago.
