### ISSUE TITLE
Switch to active application on click

### ISSUE THREAD

**Issue by oniGino** [emersion/mako#295]
Not sure how to achieve this or if its practical, but it would be great to be able to switch to the active workspace from which a notification came by clicking that notification. 

Is this even possible?

(Using Sway) or for other DE's present minimized windows, etc.

maybe this is a sway missing feature? or some combination of both?

**Comment by emersion** [comment]
* Some X11 applications can request focus or make themselves urgent when invoked
* This PR will allow users to make windows urgent based on the app_id: https://github.com/emersion/mako/pull/249
* This MR adds a toplevel handle to the notification: https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/25
* This MR allows Wayland clients to mark themselves as urgent: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/9

Closing because upstream changes are necessary.

**Comment by espen** [comment]
Is this possible now or are there still external changes required?
