### ISSUE TITLE
do-not-disturb is still disturbing

### ISSUE THREAD

**Issue by ghost** [emersion/mako#468]
I must be missing something.

Following [man 5 mako](https://man.archlinux.org/man/mako.5.en), I've put:
```
[mode=do-not-disturb]
invisible=1
```

in my config file.

Then I add the mode with `makoctl mode -a do-not-disturb`.

But I'm still receiving all the notifications.

**Comment by dR3b** [comment]
Same! I tried it this way:
```
~ » makoctl dismiss -a
~ » notify-send "test"
```
The dialog box with: "test" appeared in the corner...

**Comment by hendursaga** [comment]
Does `makoctl mode` list "do-not-disturb" or no?

**Comment by parisni** [comment]
Hi same here.

> Does makoctl mode list "do-not-disturb" or no?

only returns default.

**Comment by parisni** [comment]
made it work:
```shell
# added to config
[mode=hide]
invisible=1

makoctl mode -s hide
makoctl mode -a hide # hide the notif
makoctl mode -r hide # restore notif + show the hidden notif
```

maybe the dash in do-not-disturb, i don't know

**Comment by guttermonk** [comment]
@parisni thank you! That was a big help.

I wrote a short script to toggle "do not disturb" on and off:
```
#!/bin/bash

# Toggle DND
	if [ "$(makoctl mode)" == "dnd" ]; then
	# DND OFF
		makoctl mode -r dnd && echo "DND Mode OFF"
	else
	# DND ON
		makoctl mode -s dnd && echo "DND Mode ON"
	fi
```

Here's the module:
```
"custom/mako": {
    "on-click": "~/.config/hypr/scripts/notifications-toggle-dnd",
	"format": "DND {icon}",
	"format-icons": {
      "activated": " ",
      "deactivated": " ",
	},
    "tooltip": true,
	"tooltip-format": "Toggle DND on/off",
},
```
Does anyone know how to make the toggle icons work?

**Comment by emersion** [comment]
Beware, the copy-pasted text from the man page contains special Unicode characters: in the copy-pasted text above "‐" is U+2010, but the correct ASCII character to use "-" is U+002D. `getopts` will parse U+2010 as a positional argument instead of an option and as a result it will get ignored.

I've pushed 637365585d23 to print an error instead of silently ignoring unused positional arguments.

Note, a toggle flag has been added in https://github.com/emersion/mako/pull/502.
